### ISSUE TITLE
Data requirements

### ISSUE THREAD

**Issue by skeating** [UCLH-DHCT/emap#31]
What data do our users require? What sort of queries will they be making?

How live does it have to be? I'm guessing 10 minutes is ok, 60 minutes isn't.

How long do we need to keep live data for? Can we delete data older than eg. 7 days? This could mitigate storage problems.

**Comment by jeremyestein** [comment]
Closing because this is a requirement, not a task.
For design discussion see https://github.com/UCLH-DHCT/emap/blob/jeremy/hf-data/docs/dev/features/waveform_hf_data.md
