### ISSUE TITLE
performance checks

### ISSUE THREAD

**Issue by skeating** [UCLH-DHCT/emap#32]
Performance metrics that we need to watch:

- How much CPU time does the waveform HL7 reader take to parse HL7 and generate interchange messages?
- Can core proc process waveform messages quicker than the rate at which they're being produced, on top of the messages it's already processing? (live mode)
- How much does this slow down a validation run? (catchup mode)
- How much storage space does this take in the postgres DB?
- Can we run the read queries we need to do in a reasonable time?

**Comment by jeremyestein** [comment]
Closing because these are requirements not tasks.
For design discussion see https://github.com/UCLH-DHCT/emap/blob/jeremy/hf-data/docs/dev/features/waveform_hf_data.md
