### ISSUE TITLE
Make hl7-reader read HL7 from text files

### ISSUE THREAD

**Issue by jeremyestein** [UCLH-DHCT/emap#53]
Compressed or uncompressed HL7 dumps will be useful for testing and validation, so it needs to be able to read from one.

**Comment by Asif-Healthcare** [comment]
To test and validate HL7 message dumps, you can handle both compressed and uncompressed files. For uncompressed HL7, use libraries like `hl7apy` (Python) or `HAPI HL7` (Java) to read and parse the messages. For compressed dumps, decompress first using tools like `gzip` or `zipfile`, then process the HL7 content. Mirth Connect can also handle both formats for validation by setting up a channel to read, decompress if needed, and validate the messages.
